[metadata]
name = "memory-stress"

[global]
plan = "graphsync"
case = "stress"
total_instances = 5
builder = "docker:go"
runner = "cluster:k8s"

[global.build_config]
push_registry=true
go_proxy_mode="remote"
go_proxy_url="http://localhost:8081"
registry_type="aws"

[global.run.test_params]
size      = "1GB"
latencies = '["20ms"]'
bandwidths = '["10"]'
concurrency = "8"
chunk_size = "20"
links_per_level = "1024"
raw_leaves = "true"
disk_store = "true"
memory_snapshots = "detailed"
compare_http = "false"
max_in_progress_requests = "20"
max_memory_per_peer = "32MiB"
max_memory_total = "1GiB"
unlimited_bandwidth_case = "false"
estuary_client = "true"
block_diagnostics = "true"
no_latency_case = "false"

[[groups]]
id = "providers"
instances = { count = 1 }
[groups.resources]
memory = "4096Mi"
cpu = "1000m"

[[groups]]
id = "requestors"
instances = { count = 4 }
[groups.resources]
memory = "4096Mi"
cpu = "1000m"
